sonar.projectKey=finance-ddd
sonar.projectName=FinalProject - Personal Finance DDD
sonar.projectVersion=1.0

# Fuentes: backend Java + frontend React
sonar.sources=backend/src/main/java,src
sonar.tests=backend/src/test/java

# Binarios Java compilados (generados por mvn compile)
sonar.java.binaries=target/classes

# Ruta real de Node.js (requerido para analizar JS/TS del frontend React)
sonar.nodejs.executable=C:/Program Files/nodejs/node.exe

# Excluir carpetas que no son codigo fuente
sonar.exclusions=**/node_modules/**,**/target/**,**/.git/**,**/public/**

# Cobertura JaCoCo (generada por mvn test)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Servidor SonarQube local
sonar.host.url=http://localhost:9000
# NO commitear el token. Pasarlo por argumento:
# sonar-scanner -Dsonar.token=TU_TOKEN
# mvn sonar:sonar -Dsonar.token=TU_TOKEN

sonar.sourceEncoding=UTF-8
